//Init select inputs
$('select').material_select();


//Searcher
$( "#search" ).keyup(function( event ) {
  var value = $(this).val();
  if ( event.which == 13 ) {
     event.preventDefault();
  }
  //console.log("Filter..."+value);
  //renderCards(filterByAttr("title",value, data));
  renderCards(applyFilters());
});

function applyTitleFilter(data){
  var value = $('#search').val();
  return filterByAttr("title",value, data);
}

function filterByAttr(attr, value, data) {
  //console.log(data);
  var value = value.toLowerCase();
  return $.grep(data, function(n, i) {
    return n[attr].toLowerCase().indexOf(value) != -1;

  });
}


function renderCards(data) {
  console.log("RENDERING");
  var html = '';
  $.each(data, function(key, value) {

    html += '<div class="col s12 m6 5"><div class="card"><div class="card__meta"><span class="card-title grey-text text-darken-4">' + value.title + '</span><p class="card-subtitle grey-text text-darken-2">' + value.description + value.Chinese'</p></div></div></div>';

    html += '</div>';
  });
  $('#card-container').html(html);

}

//DATA:
var data = [
  {
    "id": 1,
    "title": "Administrative Code",
    "description": "The City’s main source of statutory law, more detailed than the Charter",
    "Chinese": "行政法典",
    "Spanish": "Código administrativo",
    "Korean": "행정 코드",
    "French": "Code administratif",
    "Urdu": "انتظامی کوڈ",
    "Arabic": "الرمز الإداري",
    "Russian": "Административный кодекс",
    "Bangla": "প্রশাসনিক কোড",
    "Polish": "Kodeks Administracyjny",
    "French Creole": "kòd administratif"
  },
  {
    "id": 2,
    "title": "Administrative Warrant",
    "description": "",
    "Chinese": "行政授權",
    "Spanish": "Orden Administrativa (de arresto)",
    "Korean": "행정 영장",
    "French": "Mandat administratif",
    "Urdu": "انتظامی وارینٹ",
    "Arabic": "أمر إداري",
    "Russian": "Административный ордер",
    "Bangla": "প্রশাসনিক ওয়ারেন্ট",
    "Polish": "Nakaz administracyjny",
    "French Creole": "administratif manda"
  },
  {
    "id": 3,
    "title": "Adopt",
    "description": "when the Council votes to turn a bill into a law",
    "Chinese": "通過",
    "Spanish": "Adoptar Proyecto de ley (el Concejo vota hacer ley un proyecto legislativo)",
    "Korean": "채택하다",
    "French": "Adopter",
    "Urdu": "اپنانا یا منظوری",
    "Arabic": "تبنى",
    "Russian": "Принять",
    "Bangla": "দত্তক গ্রহণ করা",
    "Polish": "Przyjąć",
    "French Creole": "adopte"
  },
  {
    "id": 4,
    "title": "Adopted",
    "description": "",
    "Chinese": "通過",
    "Spanish": "Adoptado",
    "Korean": "채택 된",
    "French": "Adopté",
    "Urdu": "منظور کرنا",
    "Arabic": "اعتمد",
    "Russian": "Принятый",
    "Bangla": "গৃহীত",
    "Polish": "Przyjęty",
    "French Creole": "adòpte \n\n"
  },
  {
    "id": 5,
    "title": "Advisory Committee",
    "description": "Ensure certain aspects of PB are carried out efficiently and effectively",
    "Chinese": "諮詢委員會",
    "Spanish": "Comité Directivo",
    "Korean": "자문위원회",
    "French": "Comité consultatif",
    "Urdu": "مشاورتی کمیٹی",
    "Arabic": "اللجنة الاستشارية",
    "Russian": "Консультативный комитет",
    "Bangla": "উপদেষ্টা কমিটি",
    "Polish": "Komitet doradczy/komisja doradcza",
    "French Creole": "komite konsiltatif"
  },
  {
    "id": 6,
    "title": "Agencies",
    "description": "the entities that enforce the laws adopted by the Council and promulgate rules to assist in such enforcement",
    "Chinese": "機構",
    "Spanish": "Agencias municipales",
    "Korean": "도시 기관",
    "French": "Agences de La ville",
    "Urdu": "شہری ایجنسیاں",
    "Arabic": "وكالات المدينة",
    "Russian": "Городские агентства",
    "Bangla": "সংস্থা",
    "Polish": "Agencje",
    "French Creole": "ajans"
  },
  {
    "id": 7,
    "title": "Agenda",
    "description": "a list, plan, outline, or the like, of things to be done, matters to be acted or voted upon",
    "Chinese": "議程",
    "Spanish": "agenda",
    "Korean": "의사일정",
    "French": "Ordre du jour",
    "Urdu": "ایجنڈا",
    "Arabic": "جدول الأعمال",
    "Russian": "Повестка дня",
    "Bangla": "আলোচ্য সূচি",
    "Polish": "Porządek obrad",
    "French Creole": "ajanda"
  },
  {
    "id": 8,
    "title": "Aging requirement",
    "description": "the state law requirement that a proposed bill be placed on the Council Members’ desks at least seven calendar days, excluding Sundays, before the Stated meeting at which the bill will be voted on",
    "Chinese": "時效要求",
    "Spanish": "Requisito de envejecimiento",
    "Korean": "시효 조건 or 시효 기간",
    "French": "Exigence de vieillissement",
    "Urdu": "عمر کی حد",
    "Arabic": "متطلبات الشيخوخة",
    "Russian": "Закон, согласно которому новый билль должен быть положен на стол Спикера готсовета за неделю до его подписания",
    "Bangla": "বার্ধক্য প্রয়োজনীয়তা",
    "Polish": "przepis wymagający aby projekt ustawy został zgłoszony do Rady Miasta na co najmniej siedem dni przed posiedzeniem",
    "French Creole": "kondisyon laj"
  },
  {
    "id": 9,
    "title": "Allocation",
    "description": "A sum of money within an appropriation that is set aside for a specific purpose.",
    "Chinese": "分配",
    "Spanish": "Asignación",
    "Korean": "배당 or 배당액",
    "French": "allocation",
    "Urdu": "مختص کرنا",
    "Arabic": "توزيع",
    "Russian": "распределение",
    "Bangla": "বরাদ্দ",
    "Polish": "Alokacja środków",
    "French Creole": "alokasyon"
  },
  {
    "id": 10,
    "title": "Amendment",
    "description": "changing the text of an existing bill or law.",
    "Chinese": "修訂",
    "Spanish": "Enmienda",
    "Korean": "개정 or 수정 조항",
    "French": "Amendement",
    "Urdu": "ترمیم",
    "Arabic": "تعديل",
    "Russian": "поправка",
    "Bangla": "সংশোধনী",
    "Polish": "Poprawka",
    "French Creole": "amandman"
  },
  {
    "id": 11,
    "title": "Appropriation",
    "description": "The amount of money identified in the budget for expenditure by an agency, generally divided into a number of smaller “units of appropriation.”",
    "Chinese": "撥款",
    "Spanish": "Apropiación",
    "Korean": "할당금",
    "French": "appropriation de capitale",
    "Urdu": "مختص کرنا یا اختصاص",
    "Arabic": "استيلاء",
    "Russian": "ассигнование",
    "Bangla": "অনুমোদন",
    "Polish": "Asygnowanie  funduszy",
    "French Creole": "afektasyon"
  },
  {
    "id": 12,
    "title": "Asylum",
    "description": "Protection or safe place given to someone who has left a country orplace for politcal reasons",
    "Chinese": "避難",
    "Spanish": "Asilo",
    "Korean": "피신처; 도피처; 보호 시설",
    "French": "Asile",
    "Urdu": "پناہ",
    "Arabic": "اللجوء",
    "Russian": "убежище",
    "Bangla": "আশ্রয়",
    "Polish": "Azyl",
    "French Creole": "asyòm"
  },
  {
    "id": 13,
    "title": "Baseline",
    "description": "Funding included in the Executive Budget.",
    "Chinese": "永久經費",
    "Spanish": "Financiación garantizada (should confirm Spanish translation)",
    "Korean": "예산집행에 포함된 자금",
    "French": "Données de réference",
    "Urdu": "بنیادی حد",
    "Arabic": "خط الاساس",
    "Russian": "Средства, включенные в исполнительный бюджет",
    "Bangla": "কার্যনির্বাহী বাজেটে",
    "Polish": "fundusze w budżecie bazowym/wyjściowym",
    "French Creole": ""
  },
  {
    "id": 14,
    "title": "Bill/Legislation",
    "description": "a piece of legislation before it is adopted into law",
    "Chinese": "法案",
    "Spanish": "Legislación",
    "Korean": "법안",
    "French": "projet de loi",
    "Urdu": "قانون سازی",
    "Arabic": "تشريع",
    "Russian": "Законопроект",
    "Bangla": "বিল",
    "Polish": "projekt ustawy",
    "French Creole": "lejislasyon"
  },
  {
    "id": 15,
    "title": "Briefing",
    "description": "Information that is given to someone just before they do something, or a meeting where this happens",
    "Chinese": "簡報",
    "Spanish": "sesión informativa",
    "Korean": "요약 보고",
    "French": "Réunion d’information",
    "Urdu": "بریفنگ",
    "Arabic": "توجيهات",
    "Russian": "брифинг",
    "Bangla": "ব্রিফিং/সংবাদ সম্মেলন",
    "Polish": "briefing",
    "French Creole": "an brèf"
  },
  {
    "id": 16,
    "title": "Budget",
    "description": "Financial plan that lists expected expenses and income for during a particular period",
    "Chinese": "預算",
    "Spanish": "Presupuesto",
    "Korean": "예산",
    "French": "Budget",
    "Urdu": "بجٹ",
    "Arabic": "ميزانية",
    "Russian": "бюджет",
    "Bangla": "বাজেট",
    "Polish": "budżet",
    "French Creole": "bidjè"
  },
  {
    "id": 17,
    "title": "Budget Cap",
    "description": "The difference produced when planned spending exceeds planned revenues in a given fiscal year",
    "Chinese": "預算短缺",
    "Spanish": "Limite del Presupuesto",
    "Korean": "예산 한도",
    "French": "Plafond budgétaire",
    "Urdu": "بجٹ کی حد",
    "Arabic": "سقف الميزانية",
    "Russian": "Предел бюджета",
    "Bangla": "বাজেট ক্যাপ",
    "Polish": "limit wydatków",
    "French Creole": "bidjè kap"
  },
  {
    "id": 18,
    "title": "Budget Delegate",
    "description": "Volunteers who turn ideas into project proposals for the vote.",
    "Chinese": "預算委託",
    "Spanish": "Delegados de Presupuesto",
    "Korean": "예산 대리자 or 예산 대표",
    "French": "Délégué budgétaire",
    "Urdu": "رضاکار جو خیالات کو ایوان میں ووٹ کےلئے  منصوبے کی شکل دیتے ہیں",
    "Arabic": "مندوب الميزانية",
    "Russian": "Бюджета по программам делегат",
    "Bangla": "বাজেট প্রতিনিধি",
    "Polish": "delegat budżetowy",
    "French Creole": "bidjè delege"
  },
  {
    "id": 19,
    "title": "Budget Modification",
    "description": "A change in an amount in any portion of the Adopted Expense or Review budgets during the fiscal year.",
    "Chinese": "預算修改",
    "Spanish": "Modificación del Presupuesto",
    "Korean": "예산 수정",
    "French": "modification du budget",
    "Urdu": "بجٹ میں ترمیم",
    "Arabic": "تعديل الميزانية",
    "Russian": "Изменение бюджета",
    "Bangla": "বাজেট সংশোধনী",
    "Polish": "modyfikacja budżetu",
    "French Creole": "bidjè modifikasyon"
  },
  {
    "id": 20,
    "title": "Budget Surplus",
    "description": "The difference produced when planned revenues exceed planned spending in a given fiscal year.",
    "Chinese": "預算盈餘",
    "Spanish": "Exceso del Presupuesto",
    "Korean": "예산 여분",
    "French": "Excédent budgétaire",
    "Urdu": "اضافی بجٹ",
    "Arabic": "فائض الميزانية",
    "Russian": "Бюджетный профицит",
    "Bangla": "বাজেট উদবৃত্য",
    "Polish": "nadwyżka budżetowa",
    "French Creole": "bidjè sipli"
  },
  {
    "id": 21,
    "title": "Capital Appropriation",
    "description": "The amount of money allocated to a specific budget line in the Capital Budget",
    "Chinese": "資金撥款",
    "Spanish": "Asignación de capital",
    "Korean": "자본 배분",
    "French": "appropriation de capitale",
    "Urdu": "مالی اختصاص",
    "Arabic": "مخصصات رأس المال",
    "Russian": "Капитальные ассигнования",
    "Bangla": "ক্যাপিটাল অনুমোদন",
    "Polish": "Środki kapitałowe na określony cel",
    "French Creole": "kapital afektasyon"
  },
  {
    "id": 22,
    "title": "Capital Commitments",
    "description": "Awarded contracts for capital budget spending, frequently for a multiyear period, that have been registered with the City Comptroller.",
    "Chinese": "承諾資金",
    "Spanish": "Compromisos de Capital",
    "Korean": "자본 약속",
    "French": "engagements de capitale",
    "Urdu": "سرمائے کی فراہمی کا وعدہ",
    "Arabic": "التزامات رأس المال",
    "Russian": "Обязательства по капиталу",
    "Bangla": "ক্যাপিটাল অঙ্গীকার",
    "Polish": "Zobowiązania kapitałowe",
    "French Creole": "kapital angajman"
  },
  {
    "id": 23,
    "title": "Charter",
    "description": "a body of local law that is like the City’s Constitution, laying out broad powers and principles",
    "Chinese": "章程",
    "Spanish": "Carta de leyes",
    "Korean": "헌장",
    "French": "Charte des lois locales",
    "Urdu": "مقامی ضابطے یا قوانین",
    "Arabic": "ميثاق",
    "Russian": "Хартия, свод местных законов, своего рода конституции города",
    "Bangla": "চার্টার",
    "Polish": "Czarter/statut",
    "French Creole": "lwa lokal konstitisyon"
  },
  {
    "id": 24,
    "title": "City Council",
    "description": "The legislative body of a city",
    "Chinese": "市議會",
    "Spanish": "Concejo Municipal",
    "Korean": "뉴욕시의회",
    "French": "Conseil municipal",
    "Urdu": "شہری کونسل یا سٹی کونسل",
    "Arabic": "مجلس المدينة",
    "Russian": "Городской совет",
    "Bangla": "নগর পরিষদ",
    "Polish": "Rada miasta",
    "French Creole": "konsèy vil"
  },
  {
    "id": 25,
    "title": "City Council Speaker",
    "description": "Council Member elected by its members to lead the legislative body",
    "Chinese": "市議長",
    "Spanish": "Presidente del Concejo Municipal",
    "Korean": "시의회 의장",
    "French": "Président(e) du Conseil municipal",
    "Urdu": "شہری کونسل یا سٹی کونسل کا اسپیکر",
    "Arabic": "رئيس مجلس المدينة",
    "Russian": "Спикер Горсовета",
    "Bangla": "সিটি কাউন্সিল স্পিকার",
    "Polish": "Przewodniczący Rady Miasta",
    "French Creole": "konsèy vil oratè"
  },
  {
    "id": 26,
    "title": "Committee",
    "description": "a body of Council Members who conduct oversight hearings and vote on bills in specific subject matter areas; the Council has 35 committees",
    "Chinese": "委員會",
    "Spanish": "Comité de concejales que conducen audiencias y votan sobre Proyectos de ley en áreas temáticas específicas",
    "Korean": "위원회",
    "French": "Comité",
    "Urdu": "کمیٹی",
    "Arabic": "لجنة",
    "Russian": "Комитет",
    "Bangla": "কমিটি",
    "Polish": "Komitet/Komisja \n",
    "French Creole": "komite"
  },
  {
    "id": 27,
    "title": "Committee Chair",
    "description": "the council member who is in charge of a particular committee and sets the agenda, thus serving as a gatekeeper in terms of whether or not bills will be heard",
    "Chinese": "委員會主席",
    "Spanish": "Presidente del Comité",
    "Korean": "위원회 위원장",
    "French": "Président du comité",
    "Urdu": "کمیٹی کے صدر",
    "Arabic": "رئيس اللجنة",
    "Russian": "Председатель комитета",
    "Bangla": "কমিটির সভাপতি",
    "Polish": "Przewodniczący Komisji",
    "French Creole": "chèz komite'a"
  },
  {
    "id": 28,
    "title": "Committee Counsel",
    "description": "the attorney in the Legislative Division who is an expert in the area of law relevant to a particular committee and who staffs the committee. The committee counsel drafts legislation, conducts hearings, and meets with stakeholders",
    "Chinese": "委員會律師",
    "Spanish": "Asesor Jurídico del Comité",
    "Korean": "위원회 법률 고문",
    "French": "Conseil du comité",
    "Urdu": "کمیٹی کے مشیر",
    "Arabic": "المستشار القانوني للجنة",
    "Russian": "Юридический советник комитета",
    "Bangla": "কমিটি এটর্নি",
    "Polish": "Ekspert/radca prawny",
    "French Creole": "avoka komite'a"
  },
  {
    "id": 29,
    "title": "Committee Report",
    "description": "a report prepared by the Legislative Division in anticipation of a committee hearing that summarizes the hearing topic or legislation being considered by the Council Members.",
    "Chinese": "委員會報告",
    "Spanish": "Informe del Comité",
    "Korean": "위원회 보고서",
    "French": "Rapport du Comité",
    "Urdu": "کمیٹی رپورٹ",
    "Arabic": "تقرير اللجنة",
    "Russian": "Отчет Комитета",
    "Bangla": "কমিটি প্রতিবেদন",
    "Polish": "Raport komisji",
    "French Creole": "komite rapò"
  },
  {
    "id": 30,
    "title": "Comprehensive Immigration Reform",
    "description": "Complete correction of immigration policy",
    "Chinese": "綜合移民改革",
    "Spanish": "Reforma Migratoria",
    "Korean": "광범위한 이민 개혁",
    "French": "Réforme intégrale de l'immigration",
    "Urdu": "جامع امیگریشن اصلاح",
    "Arabic": "إصلاح شامل للهجرة",
    "Russian": "Комплексная иммиграционная реформа",
    "Bangla": "কম্প্রিহেন্সিভ ইমিগ্রেশন রিফর্ম",
    "Polish": "Kompleksowa reforma imigracyjna",
    "French Creole": "Refòm imigrasyon konplè"
  },
  {
    "id": 31,
    "title": "Comptroller",
    "description": "Financial officer",
    "Chinese": "主計長",
    "Spanish": "Contralor de la Ciudad",
    "Korean": "도시 감사원장",
    "French": "Contrôleur",
    "Urdu": "کمپوٹرولر",
    "Arabic": "مراقب مالي",
    "Russian": "Ревизор",
    "Bangla": "কম্পট্রলার",
    "Polish": "Rewident",
    "French Creole": "Kontwolè"
  },
  {
    "id": 32,
    "title": "Conviction",
    "description": "Found guilty of a crime",
    "Chinese": "定罪",
    "Spanish": "Condena",
    "Korean": "신념",
    "French": "Condamnation",
    "Urdu": "جرم کا ثابت ہونا یا عدالت کی جانب سے مجرم قرار دیا جانا",
    "Arabic": "قناعة",
    "Russian": "объявлен виновным",
    "Bangla": "দণ্ড/শাস্তি",
    "Polish": "Skazanie sądowe",
    "French Creole": "kondanasyon"
  },
  {
    "id": 33,
    "title": "Council",
    "description": "the law-making entity in the City",
    "Chinese": "市議會",
    "Spanish": "Concejo Municipal",
    "Korean": "시의회",
    "French": "Conseil",
    "Urdu": "کونسل یا شہری ایوان",
    "Arabic": "مجلس",
    "Russian": "совет",
    "Bangla": "পরিষদ",
    "Polish": "Rada",
    "French Creole": "Konsèy"
  },
  {
    "id": 34,
    "title": "Council District",
    "description": "one of 51 parts of the City whose residents elect one of the Council Members to represent their interests in the Council",
    "Chinese": "市議區",
    "Spanish": "Distrito del concejo",
    "Korean": "시의회 지역구",
    "French": "District du conseil",
    "Urdu": "کونسل ڈسٹرکٹ",
    "Arabic": "منطقة المجلس",
    "Russian": "Округ Горсовета",
    "Bangla": "কাউন্সিল ডিসট্রিক্ট",
    "Polish": "Dystrykt",
    "French Creole": "Konsèy Distri a"
  },
  {
    "id": 35,
    "title": "Council Member",
    "description": "an official elected by the voting residents of a Council district to represent the district’s interests in the Council",
    "Chinese": "市議員",
    "Spanish": "Concejal, Miembro del Concejo",
    "Korean": "시의원",
    "French": "Membre du Conseil/conseiller",
    "Urdu": "کونسل کے رکن",
    "Arabic": "عضو المجلس",
    "Russian": "Член Горсовета",
    "Bangla": "কাউন্সিল সদস্য",
    "Polish": "Członek Rady/Radny",
    "French Creole": "Manm Konsèy la"
  },
  {
    "id": 36,
    "title": "Debt Limit",
    "description": "A limit on long term borrowing imposed by the state Constitution and Local Finance Law.",
    "Chinese": "借債限額",
    "Spanish": "Límite de Deuda",
    "Korean": "부채한도",
    "French": "Limite de la dette",
    "Urdu": "قرض کی حد",
    "Arabic": "حد الدين",
    "Russian": "Лимит долга",
    "Bangla": "কর্য সীমা",
    "Polish": "Limit zadłużenia",
    "French Creole": "limit dèt"
  },
  {
    "id": 37,
    "title": "Debt Service",
    "description": "Funds included in the Expense Budget for the payment of the principal and interest on long-term and short-term debt.",
    "Chinese": "債務服務",
    "Spanish": "Servicio de Deuda",
    "Korean": "채무 변제 서비스",
    "French": "Service de la dette",
    "Urdu": "قرض کی ادائگی",
    "Arabic": "خدمة الدين",
    "Russian": "Средства, включенные в бюджет для погашения долгов",
    "Bangla": "কর্য পরিশোধ সেবা",
    "Polish": "obsług/koszt długu",
    "French Creole": "dèt sèvis"
  },
  {
    "id": 38,
    "title": "Deferred Action for Childhood Arrivals (DACA)",
    "description": "",
    "Chinese": "童年抵美延緩遞解出境行動",
    "Spanish": "Consideración de Acción Diferida Para Los Llegados en la Infancia",
    "Korean": "유년기 도착 지연 조치 (DACA)",
    "French": "Action différée pour les arrivées d´enfants",
    "Urdu": "بچپن میں انے والے افراد کے خلاف کارروائی کا التوا",
    "Arabic": "الاجراءات الؤجلة للوصول لمرحلة الطفولة",
    "Russian": "Программа, защищающая права нелегальных иммигрантов, приехавших в США в детском возрасте",
    "Bangla": "শৈশবে আগতদের জন্য স্থগিত পদক্ষেপ",
    "Polish": "Program federalny zapewniający młodym imigrantom ochronę przed deportacją (THERE IS NO POLISH TERM FOR IT. I usually use the title and describe the program in Polish)",
    "French Creole": "Différé aksyon pou timoun ki (DACA)"
  },
  {
    "id": 39,
    "title": "Discretionary",
    "description": "Included because “Schedule C” is the Council’s discretionary budget.",
    "Chinese": "選擇性撥款",
    "Spanish": "Discrecional",
    "Korean": "커뮤니티 지원금",
    "French": "Facultatif",
    "Urdu": "اختیاری",
    "Arabic": "متوفر",
    "Russian": "дискреционный",
    "Bangla": "বিচক্ষনমূলক",
    "Polish": "fakultatywny/dyskrecjonalny",
    "French Creole": "Diskresyonè"
  },
  {
    "id": 40,
    "title": "District Committee",
    "description": "Provides oversight and planning throughout PB process.",
    "Chinese": "區委",
    "Spanish": "Comité del Districto",
    "Korean": "지방위원회 or 지구위원회",
    "French": "Comité de District",
    "Urdu": "ڈسٹرکٹ کمیٹی",
    "Arabic": "لجنة المقاطعة",
    "Russian": "Районный Комитет",
    "Bangla": "জেলা কমিটি",
    "Polish": "Okręgowa komisja",
    "French Creole": "Komite distri"
  },
  {
    "id": 41,
    "title": "Effective date",
    "description": "the language at the end of a local law that states when the law becomes enforceable.",
    "Chinese": "生效日期",
    "Spanish": "Fecha de vigencia",
    "Korean": "효력 발생일",
    "French": "Date d'entrée en vigeur",
    "Urdu": "مؤثر تاریخ",
    "Arabic": "تاريخ النفاذ",
    "Russian": "Дата вступления в силу",
    "Bangla": "কার্যকরের দিন",
    "Polish": "data wejścia w życie (ustawy, prawa, przepisu)",
    "French Creole": "Dat efektif \n\n"
  },
  {
    "id": 42,
    "title": "Enacted",
    "description": "Make a bill or other proposal into law",
    "Chinese": "頒布法律",
    "Spanish": "Promulgada",
    "Korean": "제정 된",
    "French": "Decreté",
    "Urdu": "نافذ کیا",
    "Arabic": "صدار",
    "Russian": "принятый",
    "Bangla": "পাশকৃত",
    "Polish": "uchwalone (prawo, ustawa)",
    "French Creole": "Adopte"
  },
  {
    "id": 43,
    "title": "Executive Budget",
    "description": "A revised budget proposal for the upcoming year and a complete financial plan for the next three years. The Council holds budget hearings and begins negotiations with the mayor.",
    "Chinese": "行政預算",
    "Spanish": "Presupuesto Ejecutivo",
    "Korean": "예산집행",
    "French": "Budget exécutif",
    "Urdu": "ایگزیکٹو بجٹ",
    "Arabic": "الميزانية التنفيذية",
    "Russian": "Исполнительный бюджет",
    "Bangla": "এক্সিকিউটিভ বাজেট",
    "Polish": "budżet wykonawczy",
    "French Creole": "Bidjè Egzekitif"
  },
  {
    "id": 44,
    "title": "Executive Order",
    "description": "A rule or order issued by the president to an executive brans of government having the force of law",
    "Chinese": "行政命令",
    "Spanish": "Orden Ejecutiva",
    "Korean": "행정 명령",
    "French": "Ordre exécutif",
    "Urdu": "ایگزیکٹو آرڈر",
    "Arabic": "أمر تنفيذي",
    "Russian": "Исполнительный указ",
    "Bangla": "নির্বাহী আদেশ",
    "Polish": "dekret wykonawczy",
    "French Creole": "Òd ekzekitif"
  },
  {
    "id": 45,
    "title": "Federal Immigration Authorities",
    "description": "",
    "Chinese": "聯邦移民局",
    "Spanish": "Autoridades Federales de Inmigración",
    "Korean": "연방 이민국",
    "French": "Autorités fédérales d'immigration",
    "Urdu": "وفاقی امیگریشن حکام",
    "Arabic": "سلطات الهجرة الاتحادية",
    "Russian": "Федеральные иммиграционные власти",
    "Bangla": "ফেডারেল অভিবাসন কর্তৃপক্ষ",
    "Polish": "Federalne władze imigracyjne",
    "French Creole": "Otorite Imigrasyon Federal"
  },
  {
    "id": 46,
    "title": "Felony",
    "description": "A crime regarded as more serious than a misdemeanor",
    "Chinese": "重罪",
    "Spanish": "Delito Mayor",
    "Korean": "중죄",
    "French": "Crime",
    "Urdu": "جرم",
    "Arabic": "جناية",
    "Russian": "Тяжелое преступление",
    "Bangla": "অপরাধ",
    "Polish": "Przestępstwo",
    "French Creole": "Krim grav"
  },
  {
    "id": 47,
    "title": "Fiscal impact statement",
    "description": "a statement prepared by the Council’s Finance Division that estimates how much a proposed local law or budget modification will cost",
    "Chinese": "財政影響報告",
    "Spanish": "Declaración de Impacto Fiscal",
    "Korean": "재정 영향 보고서",
    "French": "Déclaration d'impact fiscal",
    "Urdu": "مالیاتی امور کا بیان",
    "Arabic": "بيان الأثر المالي",
    "Russian": "Отчет о финансовом воздействии",
    "Bangla": "রাজস্ব্য বিষয়ক বিবৃতি",
    "Polish": "przewidywany koszt ustawy/modyfikacji budżetu",
    "French Creole": "Fiskal Konsekans Deklarasyon"
  },
  {
    "id": 48,
    "title": "Fiscal Year",
    "description": "An accounting period of 12 months, which in New York City begins on July 1 and ends the following June 30. By convention, each fiscal year is named for the calendar year in which it ends (fiscal year 2013 begins July 2012 and ends in June 2013).",
    "Chinese": "財政年度",
    "Spanish": "Año fiscal",
    "Korean": "회계 연도",
    "French": "Année fiscale",
    "Urdu": "مالی سال",
    "Arabic": "السنة المالية",
    "Russian": "Отчетный год",
    "Bangla": "অর্থবছর",
    "Polish": "Rok fiskalny",
    "French Creole": "Ane fiskal"
  },
  {
    "id": 49,
    "title": "Hearing",
    "description": "a meeting to discuss an oversight topic and/or bills during which the public can testify.",
    "Chinese": "聽證會",
    "Spanish": "Audiencia",
    "Korean": "청문회",
    "French": "Audition",
    "Urdu": "سماعت",
    "Arabic": "استماع",
    "Russian": "Контрольное совещание",
    "Bangla": "শুনানী",
    "Polish": "przesłuchanie",
    "French Creole": "Odyans"
  },
  {
    "id": 50,
    "title": "ICE Raids",
    "description": "Immigration enforcement roundups of immigrants",
    "Chinese": "美國移民和海關執法局突襲",
    "Spanish": "Redada de ICE",
    "Korean": "이민세관단속국의 습격",
    "French": "Raids d'immigration",
    "Urdu": "امیگریشن حکام کے چھاپے",
    "Arabic": "غارات إنفاذ الهجرة",
    "Russian": "Рейды Иммиграционно-Таможенной службы",
    "Bangla": "ইমিগ্রেশন এন্ড কাষ্টম এনফোর্সমেন্ট অভিযান",
    "Polish": "łapanki imigrantów dokonywane przez federalną agencję ICE",
    "French Creole": "ICE rèd"
  },
  {
    "id": 51,
    "title": "Immigration Court",
    "description": "",
    "Chinese": "移民法院",
    "Spanish": "Corte de Inmigración",
    "Korean": "이민법원",
    "French": "Tribunal d’immigration",
    "Urdu": "امیگریشن کورٹ",
    "Arabic": "محكمة الهجرة",
    "Russian": "Иммиграционный суд",
    "Bangla": "ইমিগ্রেশন কোর্ট/ অবিভাসন আদালত",
    "Polish": "sąd imigracyjny",
    "French Creole": "Imigrasyon tribinal"
  },
  {
    "id": 52,
    "title": "Immigration Detainer",
    "description": "An order by immigration officers authorizing the continued detention of a person in custody",
    "Chinese": "移民拘留者",
    "Spanish": "Orden de Retención de Inmigración",
    "Korean": "이민 수감자",
    "French": "Détention d'immigration",
    "Urdu": "تارکین وطن کا زیر حراست لیا جانا",
    "Arabic": "معتقل الهجرة",
    "Russian": "Требование иммиграционных властей удерживать заключенных в тюрьмах до выяснения их статуса",
    "Bangla": "অভিবাসী আটকাদেশ",
    "Polish": "nakaz zatrzymania w więzeniu",
    "French Creole": "Imigrasyon detansyon lòd"
  },
  {
    "id": 53,
    "title": "Immigration Detention",
    "description": "The action of detaining someone or the action of being detained",
    "Chinese": "移民拘留所",
    "Spanish": "Detención de inmigración",
    "Korean": "이민구치소",
    "French": "Détention de l’immigration",
    "Urdu": "تارک وطن کی گرفتاری",
    "Arabic": "احتجاز المهاجرين",
    "Russian": "Заключение в иммиграционную тюрму",
    "Bangla": "অভিবাসী ডিটেশন",
    "Polish": "aresztowanie, zatrzymanie",
    "French Creole": "Detansyon imigrasyon \n\n"
  },
  {
    "id": 54,
    "title": "Implementation",
    "description": "the process of putting a law or policy into effect",
    "Chinese": "實施",
    "Spanish": "Implementación",
    "Korean": "이행",
    "French": "Exécution",
    "Urdu": "عمل درآمد",
    "Arabic": "التنفيذ",
    "Russian": "Осуществление",
    "Bangla": "বাস্তবায়ন",
    "Polish": "wprowadzenie w życie prawa/przepisu/ustawy",
    "French Creole": "Aplikasyon"
  },
  {
    "id": 55,
    "title": "Initiative",
    "description": "An proposal to achieve a goal or solve a problem",
    "Chinese": "計劃/項目",
    "Spanish": "Iniciativa",
    "Korean": "프로그램",
    "French": "Initiative",
    "Urdu": "پہل کرنا",
    "Arabic": "مبادرة",
    "Russian": "Инициативы",
    "Bangla": "উদ্যোগ",
    "Polish": "Inicjatywa",
    "French Creole": "Inisyativ pwopozisyon"
  },
  {
    "id": 56,
    "title": "Introduced",
    "description": "To present formally",
    "Chinese": "提案/提出",
    "Spanish": "Introducción",
    "Korean": "소개 된",
    "French": "Introduit",
    "Urdu": "متعارف کرانا",
    "Arabic": "قدمت",
    "Russian": "Внесен на рассмотрение",
    "Bangla": "উপস্থাপিত",
    "Polish": "przedstawiony (projekt ustawy etc.)",
    "French Creole": "Prezante"
  },
  {
    "id": 57,
    "title": "Introduction",
    "description": "the starting point where a bill is presented publicly for the first time at a meeting of the Council and referred to the appropriate committee.",
    "Chinese": "倡議",
    "Spanish": "Introducción",
    "Korean": "입문서",
    "French": "Introduction",
    "Urdu": "تعارف",
    "Arabic": "المقدمة",
    "Russian": "Внесение на рассмотрение",
    "Bangla": "ভূমিকা",
    "Polish": "przedstawienie",
    "French Creole": "Entwodiksyon"
  },
  {
    "id": 58,
    "title": "Judicial Warrant",
    "description": "Official document approved by a judge or court that gives police permission to do certain things",
    "Chinese": "法庭調查令",
    "Spanish": "Orden Judicial (de arresto)",
    "Korean": "영장 or 사법부 영장",
    "French": "Mandat judiciaire",
    "Urdu": "جیوڈیشل وارنٹ یا   عدالتی وارنٹ",
    "Arabic": "مذكرة قضائية",
    "Russian": "Судебный ордер",
    "Bangla": "বিচারক অনুমোদিত  প্রেফতারী পরোয়ানা",
    "Polish": "Nakaz sądowy",
    "French Creole": "\n\njidisyè manda"
  },
  {
    "id": 59,
    "title": "Know Your Rights",
    "description": "",
    "Chinese": "知道你的權利",
    "Spanish": "Conozca sus Derechos",
    "Korean": "귀하의 권리를 아십시오.",
    "French": "Connaissez vos droits",
    "Urdu": "اپنے حقوق جانو",
    "Arabic": "اعرف حقوقك",
    "Russian": "Знайте свои прива",
    "Bangla": "নিজের অধিকারসমূহ জানুন",
    "Polish": "Znaj swoje prawa",
    "French Creole": "Konnen dwa ou yo"
  },
  {
    "id": 60,
    "title": "Landmark",
    "description": "a building or other place that is of outstanding historical, aesthetic, or cultural importance, often declared as such and given a special status (landmark designation) ordaining its preservation, by some authorizing organization",
    "Chinese": "里程碑",
    "Spanish": "Hito histórico",
    "Korean": "경계표",
    "French": "Point de repère",
    "Urdu": "تاریخی",
    "Arabic": "معلم معروف",
    "Russian": "Достопримечательность",
    "Bangla": "দর্শনীয় স্থান",
    "Polish": "zabytek",
    "French Creole": "\n\npiè bòn"
  },
  {
    "id": 61,
    "title": "Law",
    "description": "an enforceable requirement contained in the City’s Administrative Code or Charter",
    "Chinese": "法律",
    "Spanish": "Ley",
    "Korean": "법",
    "French": "Loi",
    "Urdu": "قانون",
    "Arabic": "القانون",
    "Russian": "Закон",
    "Bangla": "আইন",
    "Polish": "prawo",
    "French Creole": "Lwa"
  },
  {
    "id": 62,
    "title": "Law Enforcement",
    "description": "Ensuring the laws of an area are being obeyed",
    "Chinese": "執法",
    "Spanish": "Agentes del Orden Publico",
    "Korean": "법집행기관",
    "French": "Application de la loi",
    "Urdu": "قانون کا نفاذ",
    "Arabic": "تطبيق القانون",
    "Russian": "Правоохранительные органы",
    "Bangla": "আইন প্রয়োগকারী",
    "Polish": "organy ścigania",
    "French Creole": "Anfòsman lwa"
  },
  {
    "id": 63,
    "title": "Lawful Permanent Resident (green card holder)",
    "description": "green card holder",
    "Chinese": "合法永久居民",
    "Spanish": "Residente Permanente (tarjeta verde)",
    "Korean": "합법적 인 영주권자",
    "French": "Résident Permanent légal",
    "Urdu": "قانونی طور پر مستقل رہائشی",
    "Arabic": "مقيم مصرح له قانونيا",
    "Russian": "Законный постоянный житель (обладатель грин-карты)",
    "Bangla": "বৈধ স্থায়ী বাসিন্দা",
    "Polish": "osoba posiadająca status stałego rezydenta",
    "French Creole": "Rezidan pèmanan legal"
  },
  {
    "id": 64,
    "title": "Lay it over",
    "description": "to table or postpone a bill for a future hearing",
    "Chinese": "法案放置",
    "Spanish": "posponer un proyecto de ley para una audiencia future",
    "Korean": "연기하다",
    "French": "Présenter",
    "Urdu": "ملتوی کرنا",
    "Arabic": "تأجيل",
    "Russian": "Отложить",
    "Bangla": "ভবিষ্যতে শুনানির জন্য উপস্থাপন",
    "Polish": "Odroczyć",
    "French Creole": "ranvwaye"
  },
  {
    "id": 65,
    "title": "Legal Screening",
    "description": "evaluation of legal documents and status",
    "Chinese": "法律篩選",
    "Spanish": "Evaluacion Legal",
    "Korean": "법적 평가",
    "French": "Sélection légale",
    "Urdu": "قانونی اسکریننگ",
    "Arabic": "الفحص القانوني",
    "Russian": "Правовая проверка",
    "Bangla": "আইনি স্ক্রীনিং",
    "Polish": "ocena prawna",
    "French Creole": "elijib legal"
  },
  {
    "id": 66,
    "title": "Legislative process in its simplest form",
    "description": "a bill is drafted, a Council member introduces it at a Stated Meeting, a committee hearing is held, the bill is aged, the bill is voted out of the committee, more than half of the Council Members vote to adopt the bill, the Mayor signs it into law.",
    "Chinese": "最簡單的立法程序",
    "Spanish": "Proceso legislativo en su forma más simple",
    "Korean": "가장 간단한 형태의 입법 절차",
    "French": "Processus législatif dans sa forme la plus simple",
    "Urdu": "سب سے آسان شکل میں قانون سازی",
    "Arabic": "العملية التشريعية في أبسط أشكالها",
    "Russian": "Законодательный процесс в простейшей форме",
    "Bangla": "সহজতম আইনী প্রক্রিয়া",
    "Polish": "Proces ustawodawczy w najprostszej formie",
    "French Creole": "lejislatif pwosesis nan fòm ki pi senp li yo"
  },
  {
    "id": 67,
    "title": "Local law",
    "description": "an adopted bill",
    "Chinese": "本地法律",
    "Spanish": "Ley local",
    "Korean": "현지 법",
    "French": "Législation locale",
    "Urdu": "مقامی قانون",
    "Arabic": "القانون المحلي",
    "Russian": "Местное законодательство",
    "Bangla": "স্থানীয় আইন",
    "Polish": "prawo lokalne",
    "French Creole": "lokal lalwa"
  },
  {
    "id": 68,
    "title": "Local Law Enforcement",
    "description": "application of local laws",
    "Chinese": "地方執法",
    "Spanish": "Agentes del Orden Publico local",
    "Korean": "현지 법집행기관",
    "French": "Application de la loi locale",
    "Urdu": "مقامی قانون نافذ کرنے والا",
    "Arabic": "إنفاذ القانون المحلي",
    "Russian": "Местные правоохранительные органы",
    "Bangla": "স্থানীয় আইন প্রয়োগকারী সংস্থা",
    "Polish": "lokalne organy ścigania",
    "French Creole": "anfòsman lwa lokal"
  },
  {
    "id": 69,
    "title": "Mayor",
    "description": "the person in charge of executing, or implementing, the laws adopted by the Council",
    "Chinese": "市長",
    "Spanish": "Alcalde(sa)",
    "Korean": "시장",
    "French": "Maire",
    "Urdu": "میئر",
    "Arabic": "عمدة المدينة",
    "Russian": "Мэр",
    "Bangla": "মেয়র/নগর পিতা",
    "Polish": "burmistrz",
    "French Creole": "Majistra"
  },
  {
    "id": 70,
    "title": "Mayor’s Office of Immigrant Affairs (MOIA)",
    "description": "",
    "Chinese": "市長移民事務辦公室",
    "Spanish": "Oficina del Alcalde de Asuntos de Inmigrantes",
    "Korean": "시장의 이민부 (MOIA)",
    "French": "Bureau municipal des affaires des immigrants",
    "Urdu": "میئر کا دفتر برائے امور تارکین وطن",
    "Arabic": "مكتب العمدة لشؤن الهجرة\n\n",
    "Russian": "Управление мэра по делам иммигрантов",
    "Bangla": "মেয়র এর অভিবাসী বিষয়ক কার্যালয় (MOIA)",
    "Polish": "Wydział ds. Imigrantów przy Biurze Burmistrza",
    "French Creole": "Biwo Majistra a nan Zafè Imigran"
  },
  {
    "id": 71,
    "title": "Message of necessity",
    "description": "a way to avoid the aging requirement, when issued by the mayor and followed by a two-thirds vote of the Council",
    "Chinese": "必要信息",
    "Spanish": "Mensaje de necesidad",
    "Korean": "필요성있는 메시지",
    "French": "Message de nécessité",
    "Urdu": "میئر اور سٹی کونسل کی جانب سے عمر سے متعلق قانون میں ترمیم کی منظوری",
    "Arabic": "رسالة للضرورة",
    "Russian": "Сообщение о необходимости",
    "Bangla": "জরুরী বার্তা",
    "Polish": "sposób na obejście wymogu składania projektu ustawy na co najmniej siedem dni przed posiedzeniem rady",
    "French Creole": "Mesaj de nesesite"
  },
  {
    "id": 72,
    "title": "Misdemeanor",
    "description": "A minor wrongdoing; a non-indictable offence",
    "Chinese": "輕罪",
    "Spanish": "Delito Menor",
    "Korean": "경범죄",
    "French": "Délit mineur",
    "Urdu": "غلطی",
    "Arabic": "جنحة",
    "Russian": "Легкое правонарушение",
    "Bangla": "অপকর্ম",
    "Polish": "Wykroczenie",
    "French Creole": "Ofans ki pa Grav"
  },
  {
    "id": 73,
    "title": "Modified Budget",
    "description": "The Adopted Expense or Revenue Budgets are modified when revenue projections change or expenditures are reallocated during a fiscal year.",
    "Chinese": "修改預算",
    "Spanish": "Presupuesto Modificado",
    "Korean": "수정 된 예산",
    "French": "Budget modifié",
    "Urdu": "ترمیم شدہ بجٹ",
    "Arabic": "الميزانية المعدلة",
    "Russian": "Изменения бюджета по программам",
    "Bangla": "সংশোধিত বাজেট",
    "Polish": "Zmodyfikowany budżet",
    "French Creole": "Modifye bidjè"
  },
  {
    "id": 74,
    "title": "Notary Public",
    "description": "An official who has the leagl authority to say that documenbts are correctly signed or truthful",
    "Chinese": "公證人",
    "Spanish": "Notario Publico",
    "Korean": "공증인",
    "French": "Notaire",
    "Urdu": "نوٹری پبلک",
    "Arabic": "كاتب العدل",
    "Russian": "Нотариус",
    "Bangla": "নোটারি পাবলিক",
    "Polish": "Notariusz",
    "French Creole": "Notè Piblik"
  },
  {
    "id": 75,
    "title": "Notice to Appear",
    "description": "",
    "Chinese": "出庭通知",
    "Spanish": "Notificación/Aviso de Fecha de Audencia",
    "Korean": "출두 통지서",
    "French": "Citation à comparaître",
    "Urdu": "پیشی کا نوٹس",
    "Arabic": "رسالة للحضور",
    "Russian": "Уведомление о явке",
    "Bangla": "উপস্থিত হতে বলা নোটিশ",
    "Polish": "wezwanie",
    "French Creole": "Avi pou parèt"
  },
  {
    "id": 76,
    "title": "Office of Refugee Resettlement (ORR)",
    "description": "",
    "Chinese": "難民安置辦公室",
    "Spanish": "Oficina de Reubicación para Refugiados",
    "Korean": "난민 정착국 (ORR)",
    "French": "Bureau de relocalisation des réfugiés",
    "Urdu": "پناہ گزین کی بحالی کا دفتر",
    "Arabic": "مكتب إعادة توطين اللاجئين (ORR)",
    "Russian": "Управление по переселению беженцев",
    "Bangla": "রিফিউজি পুনর্বাসন অফিস",
    "Polish": "Biuro ds. przesiedlenia uchodźców",
    "French Creole": "Biwo Resettlement Refijye (ORR)"
  },
  {
    "id": 77,
    "title": "Oversight Hearing",
    "description": "Formal public audience to review issues, policy, etc.",
    "Chinese": "監督聽證會",
    "Spanish": "Audencia de Vigilancia",
    "Korean": "청문회",
    "French": "Audition de surveillance",
    "Urdu": "نگرانی کی سماعت",
    "Arabic": "جلسة الاستماع",
    "Russian": "Внутреннего надзора слушания",
    "Bangla": "নাগরিক শুনানী",
    "Polish": "przesłuchanie publiczne",
    "French Creole": "Obeyè Odyans"
  },
  {
    "id": 78,
    "title": "Participatory Budgeting",
    "description": "A democratic process in which community members directly decide how to spend part of a public budget",
    "Chinese": "參與式預算",
    "Spanish": "Presupuesto Participativo",
    "Korean": "시민 참여 예산",
    "French": "Budget participatif",
    "Urdu": "شراکت داری پر مبنی بجٹ سازی",
    "Arabic": "ميزانية تشاركية",
    "Russian": "Ориентированного участия",
    "Bangla": "অংশগ্রহণমূলক বাজেট",
    "Polish": "budżet partycypacyjny/budżet, o którym decydują przedsawiciele danej społeczności",
    "French Creole": "Patisipasyon bidjè"
  },
  {
    "id": 79,
    "title": "Passed",
    "description": "Approved by vote",
    "Chinese": "通過",
    "Spanish": "Aprobada",
    "Korean": "통과되다",
    "French": "Approuvé",
    "Urdu": "منظور یا  منظورشدہ",
    "Arabic": "مرت",
    "Russian": "Принятые",
    "Bangla": "অনুমোদিত",
    "Polish": "Zatwierdzone (prawo, ustawa, przepis)",
    "French Creole": "Apwouve"
  },
  {
    "id": 80,
    "title": "Power of Attorney",
    "description": "Alegal document in which you give another person to right to acto for you especially in financial or legal matters",
    "Chinese": "授權書",
    "Spanish": "Poder/Contrato de Mandato",
    "Korean": "위임장",
    "French": "Procuration",
    "Urdu": "قانونی اجازت نامہ",
    "Arabic": "تفويض",
    "Russian": "Доверенность",
    "Bangla": "মোক্তারনামা",
    "Polish": "Pełnomocnictwo",
    "French Creole": "Pouvwa Avoka"
  },
  {
    "id": 81,
    "title": "Preliminary Budget",
    "description": "Proposed operating and capital expenditures, and forecast of revenues for the upcoming fiscal year, plus three subsequent years. The Council holds budget hearings with city agencies and the public.",
    "Chinese": "初步預算",
    "Spanish": "Presupuesto Preliminar",
    "Korean": "예비 예산",
    "French": "Budget préliminaire",
    "Urdu": "ابتدائی بجٹ",
    "Arabic": "الميزانية الأولية",
    "Russian": "Предварительный бюджет по программам",
    "Bangla": "প্রাথমিক বাজেট",
    "Polish": "Wstępny budżet",
    "French Creole": "Preliminè bidjè"
  },
  {
    "id": 82,
    "title": "Promulgation of rules",
    "description": "when agencies create and publish additional rules and procedures to help enforce legislation adopted by the Council",
    "Chinese": "頒佈規則",
    "Spanish": "Promulgación de normas",
    "Korean": "규칙의 공포",
    "French": "Promulgation de règles",
    "Urdu": "قواعد و ضوابط",
    "Arabic": "نشر القواعد",
    "Russian": "Опубликование правил",
    "Bangla": "আইন প্রবর্তন",
    "Polish": "ogłosić przepis, ustawę, prawo",
    "French Creole": "Pwoklamasyon regleman"
  },
  {
    "id": 83,
    "title": "Proposed",
    "description": "",
    "Chinese": "提出",
    "Spanish": "Propuesto",
    "Korean": "제안된",
    "French": "Proposé",
    "Urdu": "مجوزہ",
    "Arabic": "المقترح",
    "Russian": "Предлагаемые",
    "Bangla": "প্রস্তাবিত",
    "Polish": "zaproponowany",
    "French Creole": "Pwopoze"
  },
  {
    "id": 84,
    "title": "Quorum",
    "description": "the minimum number of members of an assembly that must be present at any of its meetings to make the proceedings of that meeting valid.",
    "Chinese": "法定人數",
    "Spanish": "el quórum",
    "Korean": "정족수",
    "French": "Quorum",
    "Urdu": "کورم یا ایوان میں ممبران کی کم تعداد",
    "Arabic": "نصاب قانوني",
    "Russian": "Кворум",
    "Bangla": "কোরাম",
    "Polish": "kworum",
    "French Creole": "Kowòm"
  },
  {
    "id": 85,
    "title": "Referendum",
    "description": "a special process in which City residents cast votes on local legislation",
    "Chinese": "公投",
    "Spanish": "Referéndum",
    "Korean": "국민 투표",
    "French": "Référendum",
    "Urdu": "استصواب رائے",
    "Arabic": "استفتاء",
    "Russian": "Референдум",
    "Bangla": "গণভোট",
    "Polish": "Referendum",
    "French Creole": "Referandòm"
  },
  {
    "id": 86,
    "title": "Refugee",
    "description": "a person who has been forced to leave his country to escape persecution or violence",
    "Chinese": "難民",
    "Spanish": "Refugiado",
    "Korean": "난민  OR  피난민",
    "French": "Réfugié",
    "Urdu": "پناہ گزین",
    "Arabic": "لاجئ",
    "Russian": "Беженцы",
    "Bangla": "উদ্বাস্তু",
    "Polish": "uchodźca",
    "French Creole": "Refijye \n\n"
  },
  {
    "id": 87,
    "title": "Removal/Deporation Proceeding",
    "description": "",
    "Chinese": "處於遣返或遞解出境的程序中",
    "Spanish": "Procedimiento de Deportación",
    "Korean": "강제송환 절차",
    "French": "Procédures de Déportation",
    "Urdu": "ملک بدری / ملک بدری کے لئے کارروائی",
    "Arabic": "عملية الترحيل ، اجراءات الترحيل",
    "Russian": "Процесс по поводу депортации",
    "Bangla": "নির্বাসন প্রক্রিয়া",
    "Polish": "usunięcie/postępowanie deportacyjne",
    "French Creole": "Deportasyon Pwosè"
  },
  {
    "id": 88,
    "title": "Resolution",
    "description": "a nonbinding declaration calling on a city agency or the state or federal government to do something",
    "Chinese": "决議案",
    "Spanish": "Resolución",
    "Korean": "결의안",
    "French": "Résolution",
    "Urdu": "قرارداد",
    "Arabic": "القرار",
    "Russian": "Резолюции",
    "Bangla": "সিদ্ধান্ত",
    "Polish": "rezolucja, uchwała",
    "French Creole": "Rezolisyon"
  },
  {
    "id": 89,
    "title": "Revenue",
    "description": "",
    "Chinese": "財政收入",
    "Spanish": "Ingresos",
    "Korean": "세입",
    "French": "Recettes",
    "Urdu": "آمدنی",
    "Arabic": "إيرادات",
    "Russian": "Доход",
    "Bangla": "রাজস্ব",
    "Polish": "dochód",
    "French Creole": "Revni \n\n"
  },
  {
    "id": 90,
    "title": "Rules of the City of New York",
    "description": "regulations promulgated by City agencies",
    "Chinese": "紐約市規則",
    "Spanish": "Reglamento de la Ciudad de Nueva York",
    "Korean": "뉴욕시 규칙",
    "French": "Règles de la ville de New York",
    "Urdu": "نیویارک شہر کے قوانین",
    "Arabic": "قواعد مدينة نيويورك",
    "Russian": "Правила города Нью-Йорка",
    "Bangla": "নিউ ইয়র্ক সিটির নিয়ম কানুন",
    "Polish": "przepisy obowiązujące w mieście Nowy Jork",
    "French Creole": "Règleman nan Vil New York"
  },
  {
    "id": 91,
    "title": "Secure Communities",
    "description": "an American deportation program that relies on partnership among federal, state, and local law enforcement agencies.",
    "Chinese": "安全社區",
    "Spanish": "Comunidades Seguras",
    "Korean": "지역사회 보호  OR  시큐어 커뮤니티",
    "French": "Communautés en sécurité",
    "Urdu": "محفوظ کمیونٹی  یا محفوظ  برادری",
    "Arabic": "المجتمعات الآمنة",
    "Russian": "Обеспечение безопасности общин",
    "Bangla": "বান্ধব সম্প্রদায়সমূহ",
    "Polish": "program federalny",
    "French Creole": "kominote ki an sekirite"
  },
  {
    "id": 92,
    "title": "Session",
    "description": "each four-year period that Council Members serve; each member can only serve two terms in a row",
    "Chinese": "期限",
    "Spanish": "Sesión",
    "Korean": "세션 or 기간",
    "French": "Session",
    "Urdu": "اجلاس",
    "Arabic": "جلسة",
    "Russian": "Сессии",
    "Bangla": "সেশন",
    "Polish": "sesja",
    "French Creole": "Sesyon"
  },
  {
    "id": 93,
    "title": "Speaker",
    "description": "a Council Member who is selected by the Council to lead that body",
    "Chinese": "市議長",
    "Spanish": "Vocero(a), presidente(a)",
    "Korean": "시의회 의장",
    "French": "Intervenant",
    "Urdu": "اسپیکر",
    "Arabic": "المتحدث",
    "Russian": "Спикер Горсовета",
    "Bangla": "স্পিকার",
    "Polish": "przewodniczący",
    "French Creole": "Oratè"
  },
  {
    "id": 94,
    "title": "Speaker slip",
    "description": "###############################################################################################################################################################################################################################################################",
    "Chinese": "發言人記錄",
    "Spanish": "Formulario de orador",
    "Korean": "연사 형식",
    "French": "Billet d'intervenant",
    "Urdu": "کسی بھی شہری کی جانب سے اسپیکر سے رابطے کےلئے مخصوص فارم",
    "Arabic": "شكل إذن للتحدث",
    "Russian": "Форма, которую должен заполнить любой человек, желающий выступить в Горсовете",
    "Bangla": "বক্তব্য ইচ্ছুক ফর্ম",
    "Polish": "zgłoszenie przemawiającego",
    "French Creole": "Oratè  glise"
  },
  {
    "id": 95,
    "title": "State of the City Address",
    "description": "",
    "Chinese": "市咨文",
    "Spanish": "Discurso sobre el Estado de la Ciudad",
    "Korean": "시정연설",
    "French": "Adresse de l'état de la ville",
    "Urdu": "اسٹیٹ اف دی سٹی خطاب یا اسپیکر کا شہریوں سے سالانہ خطاب",
    "Arabic": "البيان السنوي للمدينة",
    "Russian": "Обращение мэра к жителям города",
    "Bangla": "নগর সন্ত্রান্ত সার্বিক বিবৃতি",
    "Polish": "wystąpienie burmistrza, w którym przedstawia on i podsumowuje stan miasta",
    "French Creole": "Eta nan la Vil Adrès"
  },
  {
    "id": 96,
    "title": "Stated meeting",
    "description": "a regular meeting of the full Council in which Council Members come together at City Hall to vote on bills and take other actions",
    "Chinese": "會議舉行",
    "Spanish": "Reunión declarada del concejo",
    "Korean": "명시된 회의",
    "French": "Réunion de Conseil en complet",
    "Urdu": "کونسل کا اجلاس جس میں ممبران قانون سازی میں حصہ لیتے ہیں",
    "Arabic": "الاجتماع المعلن",
    "Russian": "Полное Совещание Совета",
    "Bangla": "অধিবেশন",
    "Polish": "pełne posiedzenie Rady",
    "French Creole": "Reyinyon asanble"
  },
  {
    "id": 97,
    "title": "Summons",
    "description": "An order to appear before a magistrate or the document containing such an order",
    "Chinese": "傳票",
    "Spanish": "Orden de comparecencia; citación",
    "Korean": "소환장",
    "French": "Citation",
    "Urdu": "پیشی  کیلئے عدالتی حکمنامہ",
    "Arabic": "استدعاء",
    "Russian": "Приказ о явке в суд",
    "Bangla": "সমন",
    "Polish": "wezwanie do stawienia się przed daną władzą/urzędem",
    "French Creole": "asignasyon"
  },
  {
    "id": 98,
    "title": "Sunset clause / expiration date",
    "description": "a clause in a bill that sets a certain date or period of time when a bill, a provision or a pilot program will end",
    "Chinese": "日期條款/截止日期",
    "Spanish": "Cláusula de vencimiento  / fecha de vencimiento",
    "Korean": "만료일",
    "French": "Clause de date d'expiration",
    "Urdu": "قانون کے ختم ہونے کی تاریخ  سے متعلق شق",
    "Arabic": "تاريخ إنتهاء الصلاحية",
    "Russian": "Дата истечения срока действия оговорки",
    "Bangla": "মেয়াদ",
    "Polish": "data wygaśnięcia ustawy",
    "French Creole": "Kondisyon ekspirasyon"
  },
  {
    "id": 99,
    "title": "Temporary Protected Status (TPS)",
    "description": "",
    "Chinese": "臨時保護狀態",
    "Spanish": "Status de Protección Temporal",
    "Korean": "임시보호상태 (TPS)",
    "French": "Statut de protection temporaire (TPS)",
    "Urdu": "عارضی محفوظ حیثیت",
    "Arabic": "حالة الحماية المؤقتة",
    "Russian": "Временный защищенный статус",
    "Bangla": "অস্থায়ী সুরক্ষা অবস্থা",
    "Polish": "tymczasowy status ochronny",
    "French Creole": "Stati pwoteksyon tanporè  TPS"
  },
  {
    "id": 100,
    "title": "Testimony",
    "description": "a formal written or spoken statement",
    "Chinese": "證詞",
    "Spanish": "testimonio",
    "Korean": "증언",
    "French": "Témoignage",
    "Urdu": "بیان",
    "Arabic": "شهادة",
    "Russian": "Свидетельские показания",
    "Bangla": "সাক্ষ্য",
    "Polish": "świadectwo",
    "French Creole": "Témoignage"
  },
  {
    "id": 101,
    "title": "U.S. Citizen",
    "description": "A legal recognized national of a state or commonwealth",
    "Chinese": "美國公民",
    "Spanish": "Ciudadano Estadunidense/Americano",
    "Korean": "미국 시민",
    "French": "Citoyen américain",
    "Urdu": "امریکی شہری",
    "Arabic": "مواطن أمريكي",
    "Russian": "Гражданин США",
    "Bangla": "আমেরিকান নাগরিক",
    "Polish": "obywatel USA",
    "French Creole": "Sitwayen Ameriken"
  },
  {
    "id": 102,
    "title": "Undocumented",
    "description": "immigrant without legal immigration papers",
    "Chinese": "無証 （無身份）",
    "Spanish": "Indocumentado",
    "Korean": "서류 미비자",
    "French": "Immigrant sans-papiers",
    "Urdu": "غیر قانونی طور پر مقیم",
    "Arabic": "غير موثقة",
    "Russian": "Иммигрант без документов",
    "Bangla": "অনথিভুক্ত অভিবাসী",
    "Polish": "nieudokumentowany",
    "French Creole": "San dokiman"
  },
  {
    "id": 103,
    "title": "Unit of Appropriation",
    "description": "An agency’s operating budget is divided into a number of units of appropriation. These units of appropriation are further divided into personal service and other personal OTPS expenditures.",
    "Chinese": "撥款單位",
    "Spanish": "Unidad de Asignación de Créditos",
    "Korean": "세출 단위",
    "French": "Unité d'Appropriation",
    "Urdu": "اختصاصی یونٹ",
    "Arabic": "وحدة الاعتمادات",
    "Russian": "Часть средств бюджета, отведенная на определенные цели",
    "Bangla": "এপ্রোপ্রিয়েশন ইউনিট",
    "Polish": "wyasygnowana jednostka funduszy budżetowych",
    "French Creole": "Inite w la appropriation"
  },
  {
    "id": 104,
    "title": "Veto",
    "description": "an action by the Mayor to disapprove an adopted bill; a vote of at least two thirds of Council Members can override a mayoral veto",
    "Chinese": "否決",
    "Spanish": "Veto",
    "Korean": "거부권",
    "French": "Veto",
    "Urdu": "ویٹو",
    "Arabic": "حق النقض",
    "Russian": "Право вето",
    "Bangla": "নিষেধ/ভেটো",
    "Polish": "weto",
    "French Creole": "Veto/ mete veto sou"
  },
  {
    "id": 105,
    "title": "Vote",
    "description": "a formal expression of preference for a proposed resolution of an issue",
    "Chinese": "投票",
    "Spanish": "voto",
    "Korean": "투표",
    "French": "Voter",
    "Urdu": "ووٹ",
    "Arabic": "التصويت",
    "Russian": "Голосование",
    "Bangla": "ভোট",
    "Polish": "głosowanie",
    "French Creole": "Vòt"
  },
  {
    "id": 106,
    "title": "Witness",
    "description": "a person who testifies at a hearing",
    "Chinese": "證人",
    "Spanish": "Testigo",
    "Korean": "증인",
    "French": "Témoin",
    "Urdu": "گواہ",
    "Arabic": "الشاهد",
    "Russian": "Свидетель",
    "Bangla": "সাক্ষী",
    "Polish": "świadek",
    "French Creole": "Temwen"
  },
  {
    "id": 107,
    "title": "Zoning",
    "description": "the establishment by local governments of districts that are restricted to various types of manufacturing, commercial, or residential use",
    "Chinese": "分區",
    "Spanish": "Zonificación",
    "Korean": "지구제",
    "French": "Zonage",
    "Urdu": "زوننگ  یا کسی بھی علاقے میں زمین کا مخصوص مقاصد کے لئے استعمال",
    "Arabic": "تقسيم",
    "Russian": "Зонирование",
    "Bangla": "আঞ্চলিকায়ন/জোনিং",
    "Polish": "podział na strefy",
    "French Creole": "zonaj"
  }];

renderCards(data);

var countries = [
  {name: 'Afghanistan', code: 'AF'},
  {name: 'Åland Islands', code: 'AX'},
  {name: 'Albania', code: 'AL'},
  {name: 'Algeria', code: 'DZ'},
  {name: 'American Samoa', code: 'AS'},
  {name: 'AndorrA', code: 'AD'},
  {name: 'Angola', code: 'AO'},
  {name: 'Anguilla', code: 'AI'},
  {name: 'Antarctica', code: 'AQ'},
  {name: 'Antigua and Barbuda', code: 'AG'},
  {name: 'Argentina', code: 'AR'},
  {name: 'Armenia', code: 'AM'},
  {name: 'Aruba', code: 'AW'},
  {name: 'Australia', code: 'AU'},
  {name: 'Austria', code: 'AT'},
  {name: 'Azerbaijan', code: 'AZ'},
  {name: 'Bahamas', code: 'BS'},
  {name: 'Bahrain', code: 'BH'},
  {name: 'Bangladesh', code: 'BD'},
  {name: 'Barbados', code: 'BB'},
  {name: 'Belarus', code: 'BY'},
  {name: 'Belgium', code: 'BE'},
  {name: 'Belize', code: 'BZ'},
  {name: 'Benin', code: 'BJ'},
  {name: 'Bermuda', code: 'BM'},
  {name: 'Bhutan', code: 'BT'},
  {name: 'Bolivia', code: 'BO'},
  {name: 'Bosnia and Herzegovina', code: 'BA'},
  {name: 'Botswana', code: 'BW'},
  {name: 'Bouvet Island', code: 'BV'},
  {name: 'Brazil', code: 'BR'},
  {name: 'British Indian Ocean Territory', code: 'IO'},
  {name: 'Brunei Darussalam', code: 'BN'},
  {name: 'Bulgaria', code: 'BG'},
  {name: 'Burkina Faso', code: 'BF'},
  {name: 'Burundi', code: 'BI'},
  {name: 'Cambodia', code: 'KH'},
  {name: 'Cameroon', code: 'CM'},
  {name: 'Canada', code: 'CA'},
  {name: 'Cape Verde', code: 'CV'},
  {name: 'Cayman Islands', code: 'KY'},
  {name: 'Central African Republic', code: 'CF'},
  {name: 'Chad', code: 'TD'},
  {name: 'Chile', code: 'CL'},
  {name: 'China', code: 'CN'},
  {name: 'Christmas Island', code: 'CX'},
  {name: 'Cocos (Keeling) Islands', code: 'CC'},
  {name: 'Colombia', code: 'CO'},
  {name: 'Comoros', code: 'KM'},
  {name: 'Congo', code: 'CG'},
  {name: 'Congo, The Democratic Republic of the', code: 'CD'},
  {name: 'Cook Islands', code: 'CK'},
  {name: 'Costa Rica', code: 'CR'},
  {name: 'Cote D\'Ivoire', code: 'CI'},
  {name: 'Croatia', code: 'HR'},
  {name: 'Cuba', code: 'CU'},
  {name: 'Cyprus', code: 'CY'},
  {name: 'Czech Republic', code: 'CZ'},
  {name: 'Denmark', code: 'DK'},
  {name: 'Djibouti', code: 'DJ'},
  {name: 'Dominica', code: 'DM'},
  {name: 'Dominican Republic', code: 'DO'},
  {name: 'Ecuador', code: 'EC'},
  {name: 'Egypt', code: 'EG'},
  {name: 'El Salvador', code: 'SV'},
  {name: 'Equatorial Guinea', code: 'GQ'},
  {name: 'Eritrea', code: 'ER'},
  {name: 'Estonia', code: 'EE'},
  {name: 'Ethiopia', code: 'ET'},
  {name: 'Falkland Islands (Malvinas)', code: 'FK'},
  {name: 'Faroe Islands', code: 'FO'},
  {name: 'Fiji', code: 'FJ'},
  {name: 'Finland', code: 'FI'},
  {name: 'France', code: 'FR'},
  {name: 'French Guiana', code: 'GF'},
  {name: 'French Polynesia', code: 'PF'},
  {name: 'French Southern Territories', code: 'TF'},
  {name: 'Gabon', code: 'GA'},
  {name: 'Gambia', code: 'GM'},
  {name: 'Georgia', code: 'GE'},
  {name: 'Germany', code: 'DE'},
  {name: 'Ghana', code: 'GH'},
  {name: 'Gibraltar', code: 'GI'},
  {name: 'Greece', code: 'GR'},
  {name: 'Greenland', code: 'GL'},
  {name: 'Grenada', code: 'GD'},
  {name: 'Guadeloupe', code: 'GP'},
  {name: 'Guam', code: 'GU'},
  {name: 'Guatemala', code: 'GT'},
  {name: 'Guernsey', code: 'GG'},
  {name: 'Guinea', code: 'GN'},
  {name: 'Guinea-Bissau', code: 'GW'},
  {name: 'Guyana', code: 'GY'},
  {name: 'Haiti', code: 'HT'},
  {name: 'Heard Island and Mcdonald Islands', code: 'HM'},
  {name: 'Holy See (Vatican City State)', code: 'VA'},
  {name: 'Honduras', code: 'HN'},
  {name: 'Hong Kong', code: 'HK'},
  {name: 'Hungary', code: 'HU'},
  {name: 'Iceland', code: 'IS'},
  {name: 'India', code: 'IN'},
  {name: 'Indonesia', code: 'ID'},
  {name: 'Iran, Islamic Republic Of', code: 'IR'},
  {name: 'Iraq', code: 'IQ'},
  {name: 'Ireland', code: 'IE'},
  {name: 'Isle of Man', code: 'IM'},
  {name: 'Israel', code: 'IL'},
  {name: 'Italy', code: 'IT'},
  {name: 'Jamaica', code: 'JM'},
  {name: 'Japan', code: 'JP'},
  {name: 'Jersey', code: 'JE'},
  {name: 'Jordan', code: 'JO'},
  {name: 'Kazakhstan', code: 'KZ'},
  {name: 'Kenya', code: 'KE'},
  {name: 'Kiribati', code: 'KI'},
  {name: 'Korea, Democratic People\'S Republic of', code: 'KP'},
  {name: 'Korea, Republic of', code: 'KR'},
  {name: 'Kuwait', code: 'KW'},
  {name: 'Kyrgyzstan', code: 'KG'},
  {name: 'Lao People\'S Democratic Republic', code: 'LA'},
  {name: 'Latvia', code: 'LV'},
  {name: 'Lebanon', code: 'LB'},
  {name: 'Lesotho', code: 'LS'},
  {name: 'Liberia', code: 'LR'},
  {name: 'Libyan Arab Jamahiriya', code: 'LY'},
  {name: 'Liechtenstein', code: 'LI'},
  {name: 'Lithuania', code: 'LT'},
  {name: 'Luxembourg', code: 'LU'},
  {name: 'Macao', code: 'MO'},
  {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'},
  {name: 'Madagascar', code: 'MG'},
  {name: 'Malawi', code: 'MW'},
  {name: 'Malaysia', code: 'MY'},
  {name: 'Maldives', code: 'MV'},
  {name: 'Mali', code: 'ML'},
  {name: 'Malta', code: 'MT'},
  {name: 'Marshall Islands', code: 'MH'},
  {name: 'Martinique', code: 'MQ'},
  {name: 'Mauritania', code: 'MR'},
  {name: 'Mauritius', code: 'MU'},
  {name: 'Mayotte', code: 'YT'},
  {name: 'Mexico', code: 'MX'},
  {name: 'Micronesia, Federated States of', code: 'FM'},
  {name: 'Moldova, Republic of', code: 'MD'},
  {name: 'Monaco', code: 'MC'},
  {name: 'Mongolia', code: 'MN'},
  {name: 'Montserrat', code: 'MS'},
  {name: 'Morocco', code: 'MA'},
  {name: 'Mozambique', code: 'MZ'},
  {name: 'Myanmar', code: 'MM'},
  {name: 'Namibia', code: 'NA'},
  {name: 'Nauru', code: 'NR'},
  {name: 'Nepal', code: 'NP'},
  {name: 'Netherlands', code: 'NL'},
  {name: 'Netherlands Antilles', code: 'AN'},
  {name: 'New Caledonia', code: 'NC'},
  {name: 'New Zealand', code: 'NZ'},
  {name: 'Nicaragua', code: 'NI'},
  {name: 'Niger', code: 'NE'},
  {name: 'Nigeria', code: 'NG'},
  {name: 'Niue', code: 'NU'},
  {name: 'Norfolk Island', code: 'NF'},
  {name: 'Northern Mariana Islands', code: 'MP'},
  {name: 'Norway', code: 'NO'},
  {name: 'Oman', code: 'OM'},
  {name: 'Pakistan', code: 'PK'},
  {name: 'Palau', code: 'PW'},
  {name: 'Palestinian Territory, Occupied', code: 'PS'},
  {name: 'Panama', code: 'PA'},
  {name: 'Papua New Guinea', code: 'PG'},
  {name: 'Paraguay', code: 'PY'},
  {name: 'Peru', code: 'PE'},
  {name: 'Philippines', code: 'PH'},
  {name: 'Pitcairn', code: 'PN'},
  {name: 'Poland', code: 'PL'},
  {name: 'Portugal', code: 'PT'},
  {name: 'Puerto Rico', code: 'PR'},
  {name: 'Qatar', code: 'QA'},
  {name: 'Reunion', code: 'RE'},
  {name: 'Romania', code: 'RO'},
  {name: 'Russian Federation', code: 'RU'},
  {name: 'RWANDA', code: 'RW'},
  {name: 'Saint Helena', code: 'SH'},
  {name: 'Saint Kitts and Nevis', code: 'KN'},
  {name: 'Saint Lucia', code: 'LC'},
  {name: 'Saint Pierre and Miquelon', code: 'PM'},
  {name: 'Saint Vincent and the Grenadines', code: 'VC'},
  {name: 'Samoa', code: 'WS'},
  {name: 'San Marino', code: 'SM'},
  {name: 'Sao Tome and Principe', code: 'ST'},
  {name: 'Saudi Arabia', code: 'SA'},
  {name: 'Senegal', code: 'SN'},
  {name: 'Serbia and Montenegro', code: 'CS'},
  {name: 'Seychelles', code: 'SC'},
  {name: 'Sierra Leone', code: 'SL'},
  {name: 'Singapore', code: 'SG'},
  {name: 'Slovakia', code: 'SK'},
  {name: 'Slovenia', code: 'SI'},
  {name: 'Solomon Islands', code: 'SB'},
  {name: 'Somalia', code: 'SO'},
  {name: 'South Africa', code: 'ZA'},
  {name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
  {name: 'Spain', code: 'ES'},
  {name: 'Sri Lanka', code: 'LK'},
  {name: 'Sudan', code: 'SD'},
  {name: 'Suriname', code: 'SR'},
  {name: 'Svalbard and Jan Mayen', code: 'SJ'},
  {name: 'Swaziland', code: 'SZ'},
  {name: 'Sweden', code: 'SE'},
  {name: 'Switzerland', code: 'CH'},
  {name: 'Syrian Arab Republic', code: 'SY'},
  {name: 'Taiwan, Province of China', code: 'TW'},
  {name: 'Tajikistan', code: 'TJ'},
  {name: 'Tanzania, United Republic of', code: 'TZ'},
  {name: 'Thailand', code: 'TH'},
  {name: 'Timor-Leste', code: 'TL'},
  {name: 'Togo', code: 'TG'},
  {name: 'Tokelau', code: 'TK'},
  {name: 'Tonga', code: 'TO'},
  {name: 'Trinidad and Tobago', code: 'TT'},
  {name: 'Tunisia', code: 'TN'},
  {name: 'Turkey', code: 'TR'},
  {name: 'Turkmenistan', code: 'TM'},
  {name: 'Turks and Caicos Islands', code: 'TC'},
  {name: 'Tuvalu', code: 'TV'},
  {name: 'Uganda', code: 'UG'},
  {name: 'Ukraine', code: 'UA'},
  {name: 'United Arab Emirates', code: 'AE'},
  {name: 'United Kingdom', code: 'GB'},
  {name: 'United States', code: 'US'},
  {name: 'United States Minor Outlying Islands', code: 'UM'},
  {name: 'Uruguay', code: 'UY'},
  {name: 'Uzbekistan', code: 'UZ'},
  {name: 'Vanuatu', code: 'VU'},
  {name: 'Venezuela', code: 'VE'},
  {name: 'Viet Nam', code: 'VN'},
  {name: 'Virgin Islands, British', code: 'VG'},
  {name: 'Virgin Islands, U.S.', code: 'VI'},
  {name: 'Wallis and Futuna', code: 'WF'},
  {name: 'Western Sahara', code: 'EH'},
  {name: 'Yemen', code: 'YE'},
  {name: 'Zambia', code: 'ZM'},
  {name: 'Zimbabwe', code: 'ZW'}
];

function initCountrySelect(){
  var selectHTML = $('#country-select');
  selectHTML.append($('<option>', {
          value: 'all',
          text : 'All'
      }));
  $.each(countries, function (i, item) {

      selectHTML.append($('<option>', {
          value: item.code,
          text : item.name
      }));
  });
  selectHTML.material_select();
}
initCountrySelect();

//FILTER EVENTS:
$("#country-select").on('change', function() {
  var value = $(this).val();
  console.log("Filter COUNTRY: "+value);
  renderCards(applyFilters());
  //renderCards(filterByAttr("country-code", value, data));
});

$(".event-type-filter").change(function() {
  renderCards(applyFilters());
  //renderCards(applyEventTypeFilter());
});

function applyCountryFilter(data){
  var value = $("#country-select").val();
  if (value == 'all'){
    value = '';
  }
  return filterByAttr("country-code", value, data);
}
function applyEventTypeFilter(data){
  var result = [];
      $('input[name="event-type-filter"]:checked').each(function() {
         console.log(this.value);
         var filtered = filterByAttr("event_type", this.value, data);
        result = mergeJSONObjectsRemovingDuplicates(result,filtered);
      });
  return result;
}

function applyFilters(){
  var eventArray = [];

  console.log("FILTERS:");
  console.log($('#search').val());
  console.log($("#country-select").val());
  console.log($('input[name="event-type-filter"]:checked').serialize());

  eventArray = applyEventTypeFilter(data);
  eventArray = applyCountryFilter(eventArray);
  eventArray = applyTitleFilter(eventArray);
  return eventArray;
}




//HELPER
function mergeJSONObjectsRemovingDuplicates(arr1, arr2){
  $.merge(arr1, arr2);

  var existingIDs = [];
  arr1 = $.grep(arr1, function(v) {
      if ($.inArray(v.id, existingIDs) !== -1) {
          return false;
      }
      else {
          existingIDs.push(v.id);
          return true;
      }
  });
  return arr1;
}
